### ISSUE TITLE
插件加载成功,指令无法使用(extra:话痨和话唠的区别?)

### ISSUE THREAD

**Issue by liuzj288** [ChenXu233/nonebot_plugin_dialectlist#10]
![image](https://user-images.githubusercontent.com/13833404/193801960-8e188c04-9272-43d4-9c62-bf9575527e7c.png)

![image](https://user-images.githubusercontent.com/13833404/193801960-8e188c04-9272-43d4-9c62-bf9575527e7c.png)

**Comment by ChenXu233** [comment]
试试用 

```昨日群话痨排行榜```

而不是

```昨日群话唠排行榜```

### 话痨和话唠百度出来的意思是一样的,所以会考虑将话唠加入指令的响应

**Comment by liuzj288** [comment]
> 试试用
> 
> `昨日群话痨排行榜`
> 
> 而不是
> 
> `昨日群话唠排行榜`
> 
> ### 话痨和话唠百度出来的意思是一样的,所以会考虑将话唠加入指令的响应

依然报错
![image](https://user-images.githubusercontent.com/13833404/193901334-d51bb948-c5ae-4d29-9508-96c1f4b73adc.png)

**Comment by ChenXu233** [comment]
> > 试试用
> > `昨日群话痨排行榜`
> > 而不是
> > `昨日群话唠排行榜`
> > ### 话痨和话唠百度出来的意思是一样的,所以会考虑将话唠加入指令的响应
> 
> 依然报错 ![image](https://user-images.githubusercontent.com/13833404/193901334-d51bb948-c5ae-4d29-9508-96c1f4b73adc.png)

# 解决方法:
## 重新安装(),然后检查拼写

## 在消息格式中包含index,nickname,chatdatanum,timecost

    dialectlist_string_format: str = '第{index}名：\n{nickname},{chatdatanum}条消息\n' #消息格式
    dialectlist_string_suffix_format: str = '你们的职业是水群吗？————MYX\n计算花费时间:{timecost}秒' #消息后缀格式

## 如:
    dialectlist_string_format: str = '{nickname}是第{index}名,ta的消息量是{chatdatanum}\n' 
    dialectlist_string_suffix_format: str = '你们话多到要我算这么多{timecost}秒了!!!' 

### 考虑到这种格式可能会产生一些问题,如不想要某些信息时候删除会报错,今后可能会有更好的实现方案(
    
# 有可能是我命名不怎么规范导致的(缩头

**Comment by ChenXu233** [comment]
新版本中已经弃用话痨排行榜这种容易打错的字作为指令，故关闭该iusse
