### ISSUE TITLE
通过nb脚手架安装插件后，在.env.prod中配置不生效

### ISSUE THREAD

**Issue by Tosd0** [ChenXu233/nonebot_plugin_dialectlist#12]
如图，插件在启动时加载完毕
![image](https://user-images.githubusercontent.com/65720409/199871679-80b9f8b7-6ff3-40ae-92a4-7b65f8cdae13.png)
配置文件如下：
![image](https://user-images.githubusercontent.com/65720409/199871754-7454ef90-a64d-4065-b51d-0c38ff93dd84.png)
重启后在群里获取，设置获取7个人，但是返回还是10个，字体配置和查询回复也没有应用QAQ
![image](https://user-images.githubusercontent.com/65720409/199872019-2bb05755-e8f2-42cc-985a-9f58821f7f8f.png)
![image](https://user-images.githubusercontent.com/65720409/199872114-0307c690-b11d-4ec8-96c0-e2c0143e94ab.png)

**Comment by Cheshire-Nya** [comment]
配置写错了，比如你应该把23行的配置写成`dialectlist_get_num = 7`，而不是`dialectlist_get_num:int = 7`

**Comment by Tosd0** [comment]
> 配置写错了，比如你应该把23行的配置写成`dialectlist_get_num = 7`，而不是`dialectlist_get_num:int = 7`

好的好的！经过修改一部分配置生效了！感谢。其次就是还有一个小问题，换行符没有生效🥲
`dialectlist_string_suffix_format = '欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒'`

**Comment by Tosd0** [comment]
好的好的！经过修改一部分配置生效了！感谢。其次就是还有一个小问题，换行符没有生效🥲
`dialectlist_string_suffix_format = '欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒'`
![6E3DE52F-58D0-48ED-8FDF-C81D25B059D9](https://user-images.githubusercontent.com/65720409/203934507-bbb83595-4369-47f8-8b1e-1e7acd2f77ad.jpeg)

**Comment by Cheshire-Nya** [comment]
> > 配置写错了，比如你应该把23行的配置写成`dialectlist_get_num = 7`，而不是`dialectlist_get_num:int = 7`
> 
> 好的好的！经过修改一部分配置生效了！感谢。其次就是还有一个小问题，换行符没有生效🥲 `dialectlist_string_suffix_format = '欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒'`

![image](https://user-images.githubusercontent.com/41470933/204030993-d84e502f-1f07-43df-ac95-1b8af546b59f.png)
env中大部分转义符需要写在双引号值中，`dialectlist_string_suffix_format = '欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒'`应该写成`dialectlist_string_suffix_format="欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒"`

**Comment by Tosd0** [comment]
> > > 配置写错了，比如你应该把23行的配置写成`dialectlist_get_num = 7`，而不是`dialectlist_get_num:int = 7`
> > 
> > 
> > 好的好的！经过修改一部分配置生效了！感谢。其次就是还有一个小问题，换行符没有生效🥲 `dialectlist_string_suffix_format = '欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒'`
> 
> ![image](https://user-images.githubusercontent.com/41470933/204030993-d84e502f-1f07-43df-ac95-1b8af546b59f.png) env中大部分转义符需要写在双引号值中，`dialectlist_string_suffix_format = '欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒'`应该写成`dialectlist_string_suffix_format="欢迎查询本群水b排行榜。 \n计算花费时间:{timecost}秒"`

好的好的！生效了，谢谢🙏☺️
