### ISSUE TITLE
Linux支持

### ISSUE THREAD

**Issue by MomentQYC** [ChenXu233/nonebot_plugin_dialectlist#17]
Linux字体总是方框，安装了libgtk依然如此
请问应该怎么做

**Comment by ChenXu233** [comment]
试试你系统里面有的字体
在配置文件里面把
https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/blob/7aa9ea1ce26f47f7ec28a39a3b55eff6fd1d4511/nonebot_plugin_dialectlist/config.py#L14
这个改成你系统里面有的字体
默认下linux是没有微软雅黑的

**Comment by MomentQYC** [comment]
> 试试你系统里面有的字体 在配置文件里面把
> 
> https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/blob/7aa9ea1ce26f47f7ec28a39a3b55eff6fd1d4511/nonebot_plugin_dialectlist/config.py#L14
> 
> 
> 这个改成你系统里面有的字体
> 默认下linux是没有微软雅黑的

感谢解答，已修复
