### ISSUE TITLE
GTK+的安装问题

### ISSUE THREAD

**Issue by MysEon** [ChenXu233/nonebot_plugin_dialectlist#18]
![image](https://user-images.githubusercontent.com/46857769/215020466-4bc874b0-7b98-4385-9e68-0dd1e17e7934.png)
请教一下,为什么我安装了GTK+,并添加到path后,还是提示我没有安装GTK+,是否需要什么配置?

**Comment by ChenXu233** [comment]
请问你是Linux系统吗?

我在Windows环境下直接通过GTK+发布的安装包安装了就能用

目前我还没有在Linux系统使用过这个插件,所以暂时没法对Linux的兼容性做出保证

**Comment by MysEon** [comment]
我是Windows11系统
