### ISSUE TITLE
【功能建议】希望能出管理员查询其他群话痨的指令

### ISSUE THREAD

**Issue by Tosd0** [ChenXu233/nonebot_plugin_dialectlist#22]
如题，希望管理员可以通过私聊或在其他群聊通过参数查询指定群号的话痨，感谢（

**Comment by ChenXu233** [comment]
仓库中最新版对这个功能进行了实现
但是有bug！
所以没有上传pypi
### 目前正常的使用方法
```/今日B话榜 -g <group_id>```
### 但是
```
/今日B话榜
Bot:请输入群号
<group_id>
```
会导致直接跳过处理函数（我也不知道为什么，问歪日佬也没有办法（

**Comment by Tosd0** [comment]
这个多简单.jpg
直接把 got 方法删掉 告诉他们必须在命令中传参就好了（）
就是打个群号没这么难吧（笑死

**Comment by ChenXu233** [comment]
最新版此功能已完成，感谢您提出的建议
