### ISSUE TITLE
绘制出的图片中文文字无法正常显示

### ISSUE THREAD

**Issue by PackageInstaller** [ChenXu233/nonebot_plugin_dialectlist#24]
![image](https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/assets/80018096/0a3fb268-f9e9-4f30-9e03-234711c991fd)
如图，系统是Arch linux,已配置`dialectlist_font = 'wqy-zenhei'#字体格式` （way-zenhei是我系统字体）

**Comment by ChenXu233** [comment]
看起来像是中文显示不出来,字体支持中文吗?

**Comment by PackageInstaller** [comment]
> 看起来像是中文显示不出来,字体支持中文吗?

这个字体中文名叫文泉驿，肯定是支持中文的

**Comment by ChenXu233** [comment]
新版本中不再打算使用 pygal 默认方式渲染，转而使用 nonebot-plugin-htmlrender 进行渲染，应该不会再出现类似的问题。
