### ISSUE TITLE
关于查询后缀消息

### ISSUE THREAD

**Issue by Tosd0** [ChenXu233/nonebot_plugin_dialectlist#25]
最近发现更新了最新版本后 消息后缀的配置项和消息发送都没了？感觉那个功能应该可以保留吧（）给有需要的人发送 是有进一步考虑还是其他原因呢(\*/ω＼*)

**Comment by ChenXu233** [comment]
抱歉，人死了有一段时间了，本来打算重构一遍插件的，一直拖着没更新......
这俩天一定更更！

**Comment by Tosd0** [comment]
如果有能帮上忙的我也可以来（）我会写屎山（笑）

**Comment by ChenXu233** [comment]
新版本2.2.1中恢复该配置文件
默认配置为不显示，将配置项```dialectlist__suffix = False```改为True即可显示
