### ISSUE TITLE
报错 filter_satement() got an unexpected keyword argument 'group_id' 

### ISSUE THREAD

**Issue by qsmmhn** [ChenXu233/nonebot_plugin_dialectlist#27]
<img width="792" alt="捕获" src="https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/assets/108866283/fbe975e8-53a0-4733-b301-5085b9db4b98">

**Comment by aknyzsd** [comment]
![Screenshot_20231026_132904_com.wujie.connect.jpg](https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/assets/121467598/d8f1576a-d02b-4f66-85ea-5ed826de8c52)
我也遇到了相同的问题

**Comment by qsmmhn** [comment]
> ![Screenshot_20231026_132904_com.wujie.connect.jpg](https://user-images.githubusercontent.com/121467598/278223805-d8f1576a-d02b-4f66-85ea-5ed826de8c52.jpg) 我也遇到了相同的问题

你解决了吗？

**Comment by aknyzsd** [comment]
并没有，最近还在为gocq发愁

**Comment by aknyzsd** [comment]
> > ![Screenshot_20231026_132904_com.wujie.connect.jpg](https://user-images.githubusercontent.com/121467598/278223805-d8f1576a-d02b-4f66-85ea-5ed826de8c52.jpg) 我也遇到了相同的问题
> 
> 你解决了吗？

并没有，还在为gocq和qsign停更发愁

**Comment by ChenXu233** [comment]
可能是前置插件chatrecorder的函数更新了，但是我最近在准备首考，暂时没有时间对这些做出调整

**Comment by ChenXu233** [comment]
非常抱歉啊，学校两周回来一次时间不太充足.....

**Comment by F1Justin** [comment]
我也遇到了同样的问题（

**Comment by rainyorange** [comment]
same

**Comment by aknyzsd** [comment]
![Image_1709457167955.png](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/121467598/a9593dca-5048-4940-8ae8-340116351918)如图所示，chatrecorder在0.3.0版本后把调用的代码改了，在init把对应的位置修改一下或许就能用了？

**Comment by qsmmhn** [comment]
> ![Image_1709457167955.png](https://private-user-images.githubusercontent.com/121467598/309538744-a9593dca-5048-4940-8ae8-340116351918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzYwNjQsIm5iZiI6MTcxMjczNTc2NCwicGF0aCI6Ii8xMjE0Njc1OTgvMzA5NTM4NzQ0LWE5NTkzZGNhLTUwNDgtNDk0MC04YWU4LTM0MDExNjM1MTkxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGI0OWJjNDgzMjkwZmE0OGY5ZjM5YTgzOTEyMDc1ODc2MjM0YmYzOWQwMmMzNmZhMjI4ZDllYWY2MzBiZDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G6D3ePSK0fm8Xj5ljIcVpJv9JlMWZFgfe8vyWFbIbyQ)如图所示，chatrecorder在0.3.0版本后把调用的代码改了，在init把对应的位置修改一下或许就能用了？
怎么搞捏，大佬

**Comment by ChenXu233** [comment]
已经修复，等待新版本上传到 pypi 后即可使用，急着用可以用仓库里的版本

**Comment by aknyzsd** [comment]
好耶！

**Comment by F1Justin** [comment]
好耶！

**Comment by ChenXu233** [comment]
已上传 pypi 。
新版指令为了防止出现话痨和话唠分不清楚的情况，更改指令为/B话榜。
这个版本有一些功能没有实现，将在未来更新

**Comment by ChenXu233** [comment]
已修复，关闭该 issue
