### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by lin6953** [ChenXu233/nonebot_plugin_dialectlist#28]
pyproject.toml里写入插件名后启动出问题，删掉以后程序正常启动

![image](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/107689301/f60bdcdc-38a8-4e2f-80c5-5f63668618ac)

**Comment by ChenXu233** [comment]
> pyproject.toml里写入插件名后启动出问题，删掉以后程序正常启动
> 
> ![image](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/107689301/f60bdcdc-38a8-4e2f-80c5-5f63668618ac)
> 

可能是nonebot一些新的机制引起的，插件已经很久没更新了，现在可能适配不了。

目前我现在还在准备高考，等6月10号结束了会抓紧时间更更插件的。 =)

**Comment by ChenXu233** [comment]
已在仓库中修复完成，目前在上传pypi的过程中遇到一些问题，明天应该能解决

**Comment by ChenXu233** [comment]
已解决，试试pypi中的新版？

**Comment by lin6953** [comment]
> 已解决，试试pypi中的新版？

好的，我晚上试试

**Comment by linya72** [comment]
> 已解决，试试pypi的新版本？

已更新，但是整个nb项目跑不起来
![image](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/107689301/6544fd7c-ca07-43a7-ae5f-f76e9c4505b7)

**Comment by linya72** [comment]
> 已解决，试试pypi的新版本？

似乎依旧是这个报错
![image](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/107689301/1d0e3c14-2bc4-4ee7-aaed-41598bd18612)

![image](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/107689301/cf5686c5-3f45-4e98-a8bc-f30af2aadcc2)

**Comment by ChenXu233** [comment]
如果问题解决了就关issue咯？
