### ISSUE TITLE
载入插件时报错

### ISSUE THREAD

**Issue by shmilyty** [ChenXu233/nonebot_plugin_dialectlist#3]
![image](https://user-images.githubusercontent.com/61276699/188079592-314fae9e-a205-48c3-a9d4-6e7f9fc51c1f.png)
又重装了一下v11的adopter，还是没有用。

**Comment by ChenXu233** [comment]
这个感觉是onebot适配器的问题，我不太清楚为什么你没有这个Module（

**Comment by liuzj288** [comment]
已解决
