### ISSUE TITLE
这个cesaa是什么依赖啊

### ISSUE THREAD

**Issue by aknyzsd** [ChenXu233/nonebot_plugin_dialectlist#30]
![image](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/121467598/b533d418-5a30-4502-b16f-638a77832c41)
试了一下我这边仓库pip下来的还是1.4.0版本所以准备自行安装一下，但是我并无在仓库内找到cesaa这个依赖是打错了嘛还是我的问题
qwq

**Comment by ChenXu233** [comment]
[cesaa](https://pypi.org/project/nonebot-plugin-cesaa/)在pypi上是存在的啊？
自行安装的话记得先把依赖pip了（
你那边的pip镜像是什么？（

**Comment by aknyzsd** [comment]
> [cesaa](https://pypi.org/project/nonebot-plugin-cesaa/)在pypi上是存在的啊？
> 自行安装的话记得先把依赖pip了（
> 你那边的pip镜像是什么？（

记不清了，应该是清华源？）

**Comment by ChenXu233** [comment]
你换成阿里云源试试？

`http://mirrors.aliyun.com/pypi/simple/`

**Comment by ChenXu233** [comment]
若没有后续问题就关闭issue咯？

**Comment by aknyzsd** [comment]
彳亍吧，我bot主板坏了，寄修还没回来就一直没测qwq

**Comment by aknyzsd** [comment]
好的没有问题了，应该是当时pip源没刷新
打扰了，非常抱歉qwq
