### ISSUE TITLE
运行时会报type错误

### ISSUE THREAD

**Issue by billyosoror** [ChenXu233/nonebot_plugin_dialectlist#31]
启动的时候会报type错误
nonebot版本号：2.3.1
pydantic版本号：2.8
![错误截图](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/53106983/5a09e9c9-27ab-4c3e-8d99-53a9f0e817c3)

**Comment by ChenXu233** [comment]
实不相瞒，报错的代码我抄的是词云的

https://github.com/he0119/nonebot-plugin-wordcloud/blob/2545ab7c553974fefeb65c4a8dbd0b8c6fdbccfb/nonebot_plugin_wordcloud/__init__.py#L108-L118

具体报错好像是因为alconna？

我这边没法复现，所以也不清楚到底是什么原因。

**Comment by billyosoror** [comment]
我是在Lagrange+nonebot部署的，我尝试alconna降级测试看看

**Comment by billyosoror** [comment]
> 实不相瞒，报错的代码我抄的是词云的
> 
> https://github.com/he0119/nonebot-plugin-wordcloud/blob/2545ab7c553974fefeb65c4a8dbd0b8c6fdbccfb/nonebot_plugin_wordcloud/__init__.py#L108-L118
> 
> 具体报错好像是因为alconna？
> 
> 我这边没法复现，所以也不清楚到底是什么原因。

问题解决了，我在代码里修改了Alconna方法，现在正常运行了）
![fix](https://github.com/ChenXu233/nonebot_plugin_dialectlist/assets/53106983/19808641-6cc3-46e1-b042-19ef9a5200a7)

**Comment by ChenXu233** [comment]
新版本已解决
