### ISSUE TITLE
换行失败

### ISSUE THREAD

**Issue by qsmmhn** [ChenXu233/nonebot_plugin_dialectlist#34]
我这里这个参数dialectlist__string_format，\n没有实现换行效果，还是直接输出原字符
![1](https://github.com/user-attachments/assets/27547340-9410-4c9a-90ff-62b87b862fea)

**Comment by ChenXu233** [comment]
能否让我看看你写的配置文件？
抑或是这就是原本的配置？

**Comment by ChenXu233** [comment]
我没遇到这样的问题。
我怀疑可能是你协议端的问题。请你发送一下你的协议端和版本号。
![image](https://github.com/user-attachments/assets/23e5e1f7-e7fd-41b5-9029-69a36ec59620)
![e9462ed8ff6e26f506cce95f87e2dfdc](https://github.com/user-attachments/assets/2495db4e-c6f0-448b-9907-8c8e1aa3ea87)

### 它在我的电脑上可以很好的运行。。。

**Comment by qsmmhn** [comment]
呃，换成双引号后好了。简介那里是单引号，而且还漏了一个反斜杠

**Comment by ChenXu233** [comment]
好的，我会把readme改了

**Comment by ChenXu233** [comment]
已修复
