### ISSUE TITLE
nonebot-plugin-orm检测到新的升级操作阻断启动

### ISSUE THREAD

**Issue by ZihuaGaoCHN** [ChenXu233/nonebot_plugin_dialectlist#37]
```powershell
[ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\starlette\routing.py", line 730, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\用户\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 84, in init_orm
    await greenlet_spawn(migrate.check, alembic_config)
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\用户\Bot\.venv\Lib\site-packages\nonebot_plugin_orm\migrate.py", line 572, in check
    raise AutogenerateDiffsDetected(f"检测到新的升级操作:\n{pformat(diffs)}")
nonebot_plugin_orm.exception.AutogenerateDiffsDetected: 检测到新的升级操作:
[('add_table',
  Table('nonebot_plugin_dialectlist_messagecountcache', MetaData(), Column('id', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, primary_key=True, nullable=False), Column('time', DateTime(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False), Column('session_id', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False), Column('session_bnum', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False), schema=None)),
 ('add_index',
  Index('ix_nonebot_plugin_dialectlist_messagecountcache_session_id', Column('session_id', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False)))]

[ERROR] uvicorn | Application startup failed. Exiting.
```

nonebot-plugin-chatrecorder和nonebot-plugin-orm均已安装

**Comment by ChenXu233** [comment]
由于最新版本带来了数据库缓存，使得数据库内容发生变动，nonebot-plugin-orm会阻断启动。

解决方法：
可以看看文档
https://nonebot.dev/docs/best-practice/database/user#upgrade

**Comment by ZihuaGaoCHN** [comment]
尝试nb orm upgrade后依然无法启动，nb orm check后报错
```powershell
Error: 检测到新的升级操作:
[('add_table',
  Table('nonebot_plugin_dialectlist_messagecountcache', MetaData(), Column('id', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, primary_key=True, nullable=False), Column('time', DateTime(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False), Column('session_id', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False), Column('session_bnum', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False), schema=None)),
 ('add_index',
  Index('ix_nonebot_plugin_dialectlist_messagecountcache_session_id', Column('session_id', Integer(), table=<nonebot_plugin_dialectlist_messagecountcache>, nullable=False)))]
```

**Comment by ChenXu233** [comment]
试试
```powershell
nb orm revision -m "init dialectlist" --branch-label nonebot_plugin_dialectlist
```
然后再nb orm upgrade

参考：
https://nonebot.dev/docs/best-practice/database/developer/#首次迁移

**Comment by ZihuaGaoCHN** [comment]
已解决，感谢！

**Comment by Tosd0** [comment]
在运行 `nb orm revision -m "init dialectlist" --branch-label nonebot_plugin_dialectlist` 命令的时候出现报错如下，求帮忙看看：


```
C:\Users\Administrator\Desktop\bot\gzbot3>nb orm revision -m "init dialectlist" --branch-label nonebot_plugin_dialectlist
使用 Python: C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Scripts\python.exe
09-30 18:06:26 [SUCCESS] nonebot | NoneBot is initializing...
09-30 18:06:26 [INFO] nonebot | Current Env: prod
09-30 18:06:27 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_steam_info"
09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session_orm"
09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_cesaa"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dialectlist"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "welcome" from "src.plugins.welcome"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_longtu"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_color_see_see"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "osumatch" from "src.plugins.osumatch"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_sticker_saver"
09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "config" from "src.plugins.config"
09-30 18:06:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordcloud"
09-30 18:06:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_handle"
09-30 18:06:31 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_tortoise_orm"
09-30 18:06:31 [SUCCESS] nonebot_plugin_tortoise_orm | 数据库: 添加模型 learning_chat: nonebot_plugin_learning_chat.models
C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\pydantic\_internal\_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed
  warnings.warn(message, UserWarning)
09-30 18:06:34 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_learning_chat"
09-30 18:06:34 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordle"
09-30 18:06:34 [DEBUG] alembic | Context impl SQLiteImpl.
09-30 18:06:34 [DEBUG] alembic | Will assume non-transactional DDL.
09-30 18:06:34 [DEBUG] alembic | Detected added table 'nonebot_plugin_dialectlist_messagecountcache'
09-30 18:06:34 [DEBUG] alembic | Detected added index ''ix_nonebot_plugin_dialectlist_messagecountcache_session_id'' on '('session_id',)'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 250, in _catch_revision_errors
    yield
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 681, in generate_revision
    self.revision_map.get_revisions(head),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 544, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 778, in _resolve_revision_number
    current_head = self.get_current_head(branch_label)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 504, in get_current_head
    current_heads = self.filter_for_lineage(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 700, in filter_for_lineage
    return tuple(
           ^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 703, in <genexpr>
    if self._shares_lineage(
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 721, in _shares_lineage
    resolved_test_against_revs = [
                                 ^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 723, in <listcomp>
    self._revision_for_ident(test_against_rev)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 637, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'nonebot_plugin_dialectlist'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot_plugin_orm\__main__.py", line 283, in main
    orm(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1657, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot_plugin_orm\__main__.py", line 97, in move_script
    for script in scripts:
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\autogenerate\api.py", line 650, in generate_scripts
    yield self._to_script(generated_revision)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\autogenerate\api.py", line 555, in _to_script
    return self.script_directory.generate_revision(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 672, in generate_revision
    with self._catch_revision_errors(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 282, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'nonebot_plugin_dialectlist'
```

**Comment by ChenXu233** [comment]
> 在运行 `nb orm revision -m "init dialectlist" --branch-label nonebot_plugin_dialectlist` 命令的时候出现报错如下，求帮忙看看：
> 
> ```
> C:\Users\Administrator\Desktop\bot\gzbot3>nb orm revision -m "init dialectlist" --branch-label nonebot_plugin_dialectlist
> 使用 Python: C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Scripts\python.exe
> 09-30 18:06:26 [SUCCESS] nonebot | NoneBot is initializing...
> 09-30 18:06:26 [INFO] nonebot | Current Env: prod
> 09-30 18:06:27 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
> 09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
> 09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
> 09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
> 09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
> 09-30 18:06:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_steam_info"
> 09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
> 09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session"
> 09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_session_orm"
> 09-30 18:06:28 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_userinfo"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_cesaa"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_dialectlist"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "welcome" from "src.plugins.welcome"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chatrecorder"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_longtu"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_uninfo"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_color_see_see"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "osumatch" from "src.plugins.osumatch"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_sticker_saver"
> 09-30 18:06:29 [SUCCESS] nonebot | Succeeded to load plugin "config" from "src.plugins.config"
> 09-30 18:06:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordcloud"
> 09-30 18:06:30 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_handle"
> 09-30 18:06:31 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_tortoise_orm"
> 09-30 18:06:31 [SUCCESS] nonebot_plugin_tortoise_orm | 数据库: 添加模型 learning_chat: nonebot_plugin_learning_chat.models
> C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\pydantic\_internal\_config.py:341: UserWarning: Valid config keys have changed in V2:
> * 'json_dumps' has been removed
> * 'json_loads' has been removed
>   warnings.warn(message, UserWarning)
> 09-30 18:06:34 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_learning_chat"
> 09-30 18:06:34 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_wordle"
> 09-30 18:06:34 [DEBUG] alembic | Context impl SQLiteImpl.
> 09-30 18:06:34 [DEBUG] alembic | Will assume non-transactional DDL.
> 09-30 18:06:34 [DEBUG] alembic | Detected added table 'nonebot_plugin_dialectlist_messagecountcache'
> 09-30 18:06:34 [DEBUG] alembic | Detected added index ''ix_nonebot_plugin_dialectlist_messagecountcache_session_id'' on '('session_id',)'
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 250, in _catch_revision_errors
>     yield
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 681, in generate_revision
>     self.revision_map.get_revisions(head),
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 544, in get_revisions
>     resolved_id, branch_label = self._resolve_revision_number(id_)
>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 778, in _resolve_revision_number
>     current_head = self.get_current_head(branch_label)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 504, in get_current_head
>     current_heads = self.filter_for_lineage(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 700, in filter_for_lineage
>     return tuple(
>            ^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 703, in <genexpr>
>     if self._shares_lineage(
>        ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 721, in _shares_lineage
>     resolved_test_against_revs = [
>                                  ^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 723, in <listcomp>
>     self._revision_for_ident(test_against_rev)
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\revision.py", line 637, in _revision_for_ident
>     raise ResolutionError(
> alembic.script.revision.ResolutionError: No such revision or branch 'nonebot_plugin_dialectlist'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 27, in <module>
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot_plugin_orm\__main__.py", line 283, in main
>     orm(*args, **kwargs)
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 1657, in _process_result
>     value = ctx.invoke(self._result_callback, value, **ctx.params)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\click\decorators.py", line 45, in new_func
>     return f(get_current_context().obj, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\nonebot_plugin_orm\__main__.py", line 97, in move_script
>     for script in scripts:
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\autogenerate\api.py", line 650, in generate_scripts
>     yield self._to_script(generated_revision)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\autogenerate\api.py", line 555, in _to_script
>     return self.script_directory.generate_revision(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 672, in generate_revision
>     with self._catch_revision_errors(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\Administrator\Desktop\bot\gzbot3\.venv\Lib\site-packages\alembic\script\base.py", line 282, in _catch_revision_errors
>     raise util.CommandError(resolution) from re
> alembic.util.exc.CommandError: Can't locate revision identified by 'nonebot_plugin_dialectlist'
> ```

奇怪了，我也不是很明白这个什么问题，直接nb orm revision试试？
