### ISSUE TITLE
排行榜图片中个人资料为男的用户没有♂标记

### ISSUE THREAD

**Issue by ZihuaGaoCHN** [ChenXu233/nonebot_plugin_dialectlist#38]
![image](https://github.com/user-attachments/assets/05e11485-cc3b-4cd3-8c22-21eea2191db1)
如图，图中第三名是我，我个人资料为男性。其他没标记♂的个人资料也是男性。

**Comment by ChenXu233** [comment]
我去！
 ~~因为大家都变成了xnn所以没人能够是♂~~

应该是上游的问题，我检查了本插件逻辑，是没有问题的。
上游返回的所有理应为male结果是unkown，导致插件不打算显示（
目前不知道是上游noebot-plugin-userinfo的问题还是napcat的问题，因为我自己的napcat环境也能复现

**Comment by ZihuaGaoCHN** [comment]
刚刚在另外一个群里试了一下，有个群友的名字后面有♂了

**Comment by ChenXu233** [comment]
~~每年国庆，都会有很多群友因为诅咒变成xnn而无法被插件dialectlist鉴定为♂~~
~~但总有不被诅咒之人，那便是阳刚之气爆满到溢出的群友，他会爆炒别的xnn群友~~

我改下代码，试试把use_cache = True 改成Flase（
理论上会降低获取速度，但是还是试试把。后面加一个配置项可以自己改什么的。
待会我会更新一个新的包到pypi（至于多久不知道，因为寝室要断电我还要洗澡电脑坚持不了那么久

**Comment by ChenXu233** [comment]
> ~每年国庆，都会有很多群友因为诅咒变成xnn而无法被插件dialectlist鉴定为♂~ ~但总有不被诅咒之人，那便是阳刚之气爆满到溢出的群友，他会爆炒别的xnn群友~
> 
> 我改下代码，试试把use_cache = True 改成Flase（ 理论上会降低获取速度，但是还是试试把。后面加一个配置项可以自己改什么的。 待会我会更新一个新的包到pypi（至于多久不知道，因为寝室要断电我还要洗澡电脑坚持不了那么久

事实证明不行，
![image](https://github.com/user-attachments/assets/98487bfc-0e56-42ef-b6b1-3e247227c659)
该为male的上游依旧返回unkown（

**Comment by ChenXu233** [comment]
> > ~每年国庆，都会有很多群友因为诅咒变成xnn而无法被插件dialectlist鉴定为♂~ ~但总有不被诅咒之人，那便是阳刚之气爆满到溢出的群友，他会爆炒别的xnn群友~
> > 我改下代码，试试把use_cache = True 改成Flase（ 理论上会降低获取速度，但是还是试试把。后面加一个配置项可以自己改什么的。 待会我会更新一个新的包到pypi（至于多久不知道，因为寝室要断电我还要洗澡电脑坚持不了那么久
> 
> 事实证明不行， ![image](https://private-user-images.githubusercontent.com/91937041/371765284-98487bfc-0e56-42ef-b6b1-3e247227c659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzQ3NzEsIm5iZiI6MTcyNzUzNDQ3MSwicGF0aCI6Ii85MTkzNzA0MS8zNzE3NjUyODQtOTg0ODdiZmMtMGU1Ni00MmVmLWI2YjEtM2UyNDcyMjdjNjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDE0NDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDA2ZTAzMGUxOTE1YzEyZTFiNzdjY2QyNjYyNmE5MTYzOWIyNzEyMTJjOTJkYTFkOTA4YjkwYjc3OWQ2N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MqFaM7v-uZ47YX1ocmtkAizXPNVEsLEf2xRTsAUzyLU) 该为male的上游依旧返回unkown（

排除了上游的上游napcat的问题
基本确定是user_info的问题，这就去开issue
![image](https://github.com/user-attachments/assets/96c99002-b83c-4aae-af02-61088f232886)

**Comment by ChenXu233** [comment]
建议更新napcat。
至少更新后在我的电脑上没出过问题

**Comment by ZihuaGaoCHN** [comment]
我是用的是LLOneBot，而不是NapCat

**Comment by ChenXu233** [comment]
> 我是用的是LLOneBot，而不是NapCat

llonebot更新一下？

**Comment by ZihuaGaoCHN** [comment]
已经是最新了

**Comment by ChenXu233** [comment]
抱歉最近有事没有看issue，现在你的llonebot还是最新吗？

**Comment by ChenXu233** [comment]
更新最新版 llonebot 以及 napcat 后我这里均无法复现这个问题，请问你这个问题还在吗？
