### ISSUE TITLE
pip install报错

### ISSUE THREAD

**Issue by YuuLuo** [ChenXu233/nonebot_plugin_dialectlist#4]
通过pip安装时会出现如下提示
![image](https://user-images.githubusercontent.com/69673808/189477303-24945d2b-f07a-4863-9574-e8e9d9457e2f.png)

**Comment by ChenXu233** [comment]
## 已经重新上传PYPI，重新pip就行了
原因是我在setup.py内把”nonebot_plugin_guild_patch“错写错成“onebot_plugin_guild_patch”了🧐
