### ISSUE TITLE
可视化文字是方框

### ISSUE THREAD

**Issue by izumishigure** [ChenXu233/nonebot_plugin_dialectlist#6]
作者大佬你好，我是从这次rc1版本开始使用你的插件的，出来的可视化图片里的文字是方框，已经安装字体插件和部分字体文件（nonebot-plugin-imageutils和ubuntu的fonts-noto）
![AG3Z5V1UVDZ2F%@WVF1K6}T](https://user-images.githubusercontent.com/110440951/193457249-6d9c1020-5919-4873-88b0-5c91926a19aa.PNG)

**Comment by ChenXu233** [comment]
https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/blob/5f066da85110ca762cb90cd24dbadb5490a311ec/nonebot_plugin_dialectlist/qqDBRecorder.py#L10

将这段代码中的font_family="SimHei"改为你系统里有的字体试试？

**Comment by ChenXu233** [comment]
# 更新了字体配置
