### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by liuzj288** [ChenXu233/nonebot_plugin_dialectlist#9]
![image](https://user-images.githubusercontent.com/13833404/193646048-c0f285d6-dfb3-4ea5-baf6-5e24b7e06304.png)

**Comment by ChenXu233** [comment]
# 已解决，再次更新即可，问题原因如下
------------------------------
由于我本地的git被我弄的一团糟，所以把这个未经测试的版本上传了（我习惯差（）

## 问题代码：
https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/blob/95c937203d2ef68bf01f33b16353e59a3919198b/nonebot_plugin_dialectlist/__init__.py#L171-L172
### 问题原因：
直接将bot信息进去，导致parameter有多层结构，从而导致错误
## 修复代码：
https://github.com/X-Skirt-X/nonebot_plugin_dialectlist/blob/7b0bf0a5722ba8cab6e6d3ccb741551db8866bdf/nonebot_plugin_dialectlist/__init__.py#L171-L172
